# SPDX-FileCopyrightText: Copyright (c) 2023 - 2024 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

defaults :
  - modulus_default
  - arch:
      - fully_connected
  # - scheduler: tf_exponential_lr
  - scheduler: cosine_annealing
  # - scheduler: cosine_annealing_warm_restarts
  - optimizer: adam
  - loss: sum
  - _self_
  
# Exponential lr
# scheduler: # exponential_lr
#   decay_rate: 0.94044485170
#   # decay_rate: 1.0
#   decay_steps: 10000


# With restarts
# scheduler:
#     T_0: 16
#     T_mult: 2
#     eta_min: 0.0

# Without restarts
scheduler:
  T_max: 100000
  eta_min: 1e-7


arch:
  fully_connected:
    nr_layers: 3
    layer_size: 128
    activation_fn: "silu"

training:
  rec_validation_freq: 1000
  rec_inference_freq: 100000
  rec_monitor_freq: 1000
  rec_constraint_freq: 2000
  max_steps : 1500000

batch_size:
  NoSlip: 100
  Interior: 1500
  Inlet: 100

graph:
  func_arch: true